---
#print-out-distribution.yml
- name: print out distribution
  hosts: localhost
  gather_facts: True
  tasks:
    - name: "print output"
      debug:
       msg: " {{ ansible_distribution }} {{ ansible_distribution_version }}"
